### ISSUE TITLE
General introduction and quick start

### ISSUE THREAD

**Issue by arne-vandamme** [ForeachOS/ax-docs-dynamic-forms-module#1]
Write the general information on Dynamic Documents.

- [x] Explain terms document, definition, view
- [x] Quick start: creating an application, add dataset, definition
- [x] Include screenshots of AdminWeb

**Comment by sgentens** [comment]
Also added documentation for

- definition version (https://across-docs.foreach.be/across-site/preview/dynamic-forms-module/0.0.1/definitions/definition-versions.html)
- document version (https://across-docs.foreach.be/across-site/preview/dynamic-forms-module/0.0.1/working-with-documents/document-versions.html)
